# fly.toml app configuration file generated for good-time-karaoke-app on 2025-09-28T16:54:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'good-time-karaoke-app'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

# Persistent volume for SQLite database
[mounts]
  source = 'karaoke_data'
  destination = '/data'
  initial_size = '1gb'
